**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
# Q1-1
import pandas as pd
df = pd.DataFrame(data)
# Q1-2
df2 = df.loc[df.num_cars > df.family_size]
print(df2.loc[(df2["job"] == "teacher") | (df2["job"] == "psychologist")])
# Q1-3
print(df.loc[(df.num_cars >= 1) | (df.family_size >= 2)])
# Q1-4
print("Unique jobs =", len(df.job.unique()), df.job.unique())

   name           job  family_size  num_cars
5  Lisa  psychologist            3         4
     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1
Unique jobs = 4 ['teacher' 'psychologist' 'data scientist' 'software developer']


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
# Type your solution here
print(weights.groupby(fruit).mean())


apple     5.00
banana    5.25
carrot    6.00
dtype: float64


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'pJS', 'pexamples', 'PHP', 'phtml'])

In [ ]:
# Type your solution here
# Q3-1
print(np.argsort(course_name))

# Q3-2 - Check for capital "P"
pcheck = np.char.startswith(course_name, "P")
print(pcheck)
  
    

[3 0 1 2 4]
[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
# Q4-1
reverse_id = student_id[::-1] 
print("Original:", student_id,"Reversed:", reverse_id)
# Q4-2
sorted_id = np.sort(student_id) 
print("3 largest values:", sorted_id[-3 :])

Original: [1023 5202 6230 1671 1682 5241 4532] Reversed: [4532 5241 1682 1671 6230 5202 1023]
3 largest values: [5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# Type your solution here
mult3 = np.arange(0, 100, 3)
mult5 = np.arange(0, 100, 5)
sum3 = np.sum(mult3)
print("Sum of all the multiples of 3 below 100:", np.sum(mult3))
print("Sum of all the multiples of 5 below 100:", np.sum(mult5))

Sum of all the multiples of 3 below 100: 1683
Sum of all the multiples of 5 below 100: 950


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
arr = np.arange(12).reshape(3,4)
print(arr)
# swap column 1 with column 2
arr[:, [2, 1]] = arr[:, [1, 2]] 
print(arr)
# Then, swap row 0 with row 1
arr[[1, 0],:] = arr[[0, 1], :] 
print(arr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]
[[ 4  6  5  7]
 [ 0  2  1  3]
 [ 8 10  9 11]]
